messagerie/chat/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import *
import uuid 

app_name = 'chat'
urlpatterns = [
    path('', GetIndexView.as_view(), name='indexChat'),
    path('chat/', GetChatView.as_view(), name='getChat'),
    path('chat/<uuid:uuid>', HandleChatView.as_view(), name='handleChat'),
    path('chat/create/', CreateChatView.as_view(), name='createChat')
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

messagerie/compte/urls.py
from django.urls import path
from .views import *

app_name = 'compte'
urlpatterns = [
    path('', index, name='index'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', CreateUserView.as_view(), name='createUser'),
    path('delete/', DeleteView.as_view(), name='deleteUser'),
]

messagerie/messagerie/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("", include('chat.urls')),
    path("admin/", admin.site.urls),
    path("compte/", include('compte.urls')),
    path("chat/", include('chat.urls')),
]

messagerie/chat/models.py
from django.db import models
from django.contrib.auth import get_user_model
from uuid import uuid4
from django.urls import reverse
import pytz


# Create your models here.
User = get_user_model()


class Chat(models.Model):
    uuid = models.UUIDField(default=uuid4, editable=False)
    name = models.CharField(default='Chat', max_length=30)
    groupe = models.BooleanField(default=False)
    users = models.ManyToManyField(User)
    adm = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name="adm")

    def rename_chat(self):
        if not self.groupe:
            users = self.users.all()
            self.name = f"{users[0]} - {users[1]}"
        self.save()

    def __str__(self):
        return self.name  
    
    def changeStatus(self, status, user):
        message = Message.objects.filter(chat=self).last()
        if message:
            if message.user != user:
                if message.status == 'sent' and status == 'delivered':
                    message.status = 'delivered'
                    message.save()
                elif message.status == 'delivered' and status == 'received':
                    message.status = status
                    message.save()
                    msgs = Message.objects.filter(chat=self)
                    msgs = msgs.exclude(status=status)
                    for msg in msgs:
                        msg.status = status
                        msg.save()
                return message.user.username
        
    
    def is_adm(self, user:User):
        return self.adm == user
    
    def get_messages(self):
        paris_timezone = pytz.timezone('Europe/Paris')
        messages = Message.objects.filter(chat=self).order_by('timestamp')
        if messages:
            for msg in messages:
                msg.timestamp = msg.timestamp.astimezone(paris_timezone)
        return messages
    
    def get_absolute_url(self):
        return reverse("chat:handleGr", args=[str(self.uuid)])


class Message(models.Model):
    typeChoices = [
                ('Info', 'info'),  
                ('Create', 'create'),  
                ("Join", "join"), 
                ("Left", "left"), 
                ("Normal", "normal")]
    statusChoices = [
                ('sent', 'Sent'),  
                ('Delivered', 'delivered'),  
                ("Received", "received"), ]

    type = models.CharField(choices=typeChoices, default='normal', max_length=6)
    status = models.CharField(choices=statusChoices, default='sent', max_length=9)
    text = models.TextField(blank=False, max_length=2000)
    timestamp = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    chat = models.ForeignKey(Chat, on_delete=models.CASCADE)

    def __str__(self):
        return self.text
        

messagerie/chat/forms.py
from django.core.validators import RegexValidator
from django import forms
from .models import Message, User, Chat

class MessageForm(forms.ModelForm):
    chat = forms.IntegerField(widget=forms.HiddenInput() ,required=True)
    text = forms.Textarea(attrs={'placeholder':'Taper le message...'})
    class Meta:
        model = Message
        fields = [
            'text',
            'chat'
        ]


class GroupForm(forms.ModelForm):
    name = forms.CharField(required=True)
    class Meta:
        model = Chat
        fields = [
            'name',
            'users'
        ]
    
        
        
    
    

messagerie/chat/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, HttpResponse
from django.views import View
from .models import User, Chat
from .forms import MessageForm, GroupForm
import pytz

# Create your views here.
class LoginRequired(LoginRequiredMixin):
    login_url = "/compte/login"


class GetIndexView(LoginRequired, View):
    def get(self, request):
        return render( request, 'chat/chat.html', {})
    
class GetChatView(LoginRequired, View):
    def get(self, request):
        latestMsgs = []
        paris_timezone = pytz.timezone('Europe/Paris')
        for chat in request.user.get_chats():
            msg = chat.get_messages().last()
            if msg:
                msg.timestamp = msg.timestamp.astimezone(paris_timezone)
                latestMsgs.append(msg)
        latestMsgs = sorted(latestMsgs, key=lambda x:x.timestamp, reverse=True)
        return render(request, 'chat/getChat.html', {'messages':latestMsgs})
    

class CreateChatView(LoginRequired, View):
    def get(self, request):
        users = User.objects.exclude(id=request.user.id).order_by('username')
        return render(request, 'chat/createChat.html', {'users': users,
                                                        'group': GroupForm()})


class HandleChatView(LoginRequired, View):
    def get(self, request, uuid):
        users = User.objects.exclude(id=request.user.id)
        chat = Chat.objects.get(uuid=uuid)
        if request.user in chat.users.all():
            messages = []
            for msg in chat.get_messages():
                dictMsg = {'date':str(msg.timestamp.date()), 'content':msg}
                messages.append(dictMsg)
            return render(request, 'chat/handleChat.html', {'messages':messages,
                                                            'chat':chat,
                                                            'users':users})
        return HttpResponse('''<div class='divtemp'> <p>Vous n'avez plus accès
                             à ce chat ou groupe</p></div>''')


class HandleGroupView(LoginRequired, View):
    def get(self, request, uuid):
        group = Chat.objects.get(uuid=uuid)
        return render(request, 'chat/chat.html', {  
            'message': MessageForm(initial={'chat':group.id}),
            'chat':group})

messagerie/chat/templates/chat/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <title>MiniChat</title>
    <style>
        :root {
            --main-bg-image: url("{% static 'images/bg.jpeg' %}");
        }
    </style>
</head>
<body>
    
    {% block content %}
    {% endblock content %}

</body>
</html>

messagerie/chat/templates/chat/chat.html
{% extends "chat/base.html" %}
{% load static %}

{% block content %}
{% if user.is_authenticated %}

    <section class="header">
        <a id="userBtn" >
            <img class="usericon" src="{% static 'images/user.png' %}" alt="usericon">
        </a>
        <nav id="usernav" class="usernav moveUsernav">
            <div class="useropt">
                <a href="{% url 'compte:logout' %}" id="logout">Logout</a>
                <a href="{% url 'compte:createUser' %}" id="updateUser">Actualiser le compte</a>
                <a href="{% url 'compte:deleteUser' %}" id="logout">Supprimer le compte</a>
            </div>
            <div class="userinfo">
                <div>
                    <div>
                        <h3>{{ user.get_username|capfirst }}</h3>
                    </div>
                    <h5>Info</h5>
                    <p>
                        {% if not user.info %}
                            Non renseigné
                        {% endif %}
                        {{ user.info }}
                    </p>
                </div>
                <div>
                    <h5>Mail</h5>
                    <p>
                        {% if not user.email %}
                            Non renseigné
                        {% endif %}
                        {{ user.email }}
                    </p>
                </div>
                <div>
                    <h5>Téléphone</h5>
                    <p>
                        {% if not user.num_tel %}
                            Non renseigné
                        {% endif %}
                        {{ user.num_tel }}
                    </p>
                </div>
            </div>  
        </nav>
        <a href="{% url 'compte:logout' %}" id="logout">
            <img class="logouticon" src="{% static 'images/logout.png' %}" alt="logouticon">
        </a>
        <div id='alert'>
            <p></p>
        </div>
    </section>

    <section class="chat">
        <header>
            <h4>Chats</h4>
            <a  id="createChatBtn">
                <img src="{% static 'images/create.png' %}" alt="createicon">
            </a>
        </header>
        <div id="create" class="create moveCreate">
            <div id="createChat" class="createChat">
                <h4>Nouveau chat</h4>
                <ul>
                    <li id="createGrBtn"><a>Créer un groupe</a></li>
                </ul>
            </div>
            <div id="createGr" class="createGr">
                <h4>Nouveau groupe</h4>
            </div>
        </div>
        <ul>
        </ul>
    </section>


    <section class="message">
        <div class="divtemp">
            <p>Sélectionner ou créer un nouveau chat.</p>
        </div>
    </section>

    <script src="{% static 'js/script.js' %}"></script>

{% endif %}
{% endblock content %}


    

messagerie/chat/templates/chat/createChat.html
{% load static %}
{% if users is not None %}
    <div id="createChat" class="createChat">
            <h4>Nouveau chat</h4>
            <ul>
                <li id="createGrBtn">Créer un groupe</li>
                {% for user in users %}
                    <li class='user' value="{{ user }}">{{ user|capfirst }}</li>
                {% endfor %}
            </ul>
        </div>

        {% if group is not None %}
            <div id="createGr" class="createGr">
                <h4>Nouveau groupe</h4>
                <label for="id_name">Nom du groupe</label>
                {{ group.name }}
                <select hidden name="users" required id="id_users" multiple>
                </select>
                <div>
                    {% for user in users %}
                    <label><input type="checkbox" id="option" value="{{ user }}"/>{{ user|capfirst }}</label>
                    {% endfor %}
                </div>
                <img src="{% static 'images/create.png' %}" alt="createicon">
            </div>
        {% endif %}
{% endif %}

messagerie/chat/templates/chat/getChat.html
{% for msg in messages %}
    {% if msg  %}
        {% if msg.status != 'received' and msg.user != user %}
        <li class='chatChild unread' id='id{{msg.chat.uuid}}'> 
        {% else %}
        <li class='chatChild' id='id{{msg.chat.uuid}}'> 
        {% endif %}
            <p>
                {% if msg.chat.groupe %}
                    {{ msg.chat|capfirst }}
                {% else %} 
                    {% for elem in msg.chat.users.all %}
                        {% if user != elem %}
                            {{ elem|capfirst }}
                        {% endif %}
                    {% endfor %}
                {% endif %}
                <span>{{ msg.timestamp.time }}</span>
            </p>
            <span>
        {% if msg.chat.groupe and msg.type == 'join' or msg.type == 'create' %}
                Nouvelles!
        {% else %}
                {% if msg.chat.groupe %}
                    {{ msg.user | capfirst }} : 
                {% endif %}
                {{ msg.text|slice:":100" }}
            </span>
        {% endif %}
            <div style='display:none;position:absolute;' > 
                <p id='id{{msg.chat.uuid}}'>
                    {% if msg.chat.groupe %}
                        {{ msg.chat|capfirst }}
                    {% else %} 
                        {% for elem in msg.chat.users.all %}
                            {% if user != elem %}
                                {{ elem|capfirst }}
                            {% endif %}
                        {% endfor %}
                    {% endif %}

            {% if msg.chat.groupe and msg.type == 'join' or msg.type == 'create' %}
                    : Nouvelles!
            {% else %}
                    {% if msg.chat.groupe %}
                        ({{ msg.user | capfirst }}) 
                    {% endif %}
                    : {{ msg.text|slice:":100" }}
            {% endif %}
            </div>
        </li>
        
    {% endif %}
{% endfor %}

messagerie/chat/templates/chat/handleChat.html
{% load static %}
        <header>
            <a id="backBtn" class='backBtn'>
                <img src="{% static "images/back.png" %}" alt="backicon">
            </a>
            {% if chat.groupe %}
            <a>{{ chat }}</a>
            <p> 
                {% with users=chat.users.all %}
                    {% for user in users %}
                        @{{user|capfirst}}
                        {% if users.last != user %}, {% endif %}
                    {% endfor %}
                {% endwith %}
            </p>
            {% else %}
                {% for elem in chat.users.all %}
                    {% if user != elem %}
            <a>          {{ elem|capfirst }}</a>
                    {% endif %}
                {% endfor %}
            <p></p>
            {% endif %}

            <a id='menuBtn'>
                <img src="{% static "images/menu.png" %}" alt="menuicon">
            </a>
        </header>
        <aside class='aside moveAside' >
            {% if chat.groupe %}
            <div class='group'>
                {% if chat.adm == user %}
                <div>
                    <label >Nouveau nom</label>
                    <div >
                        <input id='inputGr' type="text"/>
                        <img id='renameGr' src="{% static "images/save.png" %}" alt="deleteicon">
                    </div>
                    <a id='deleteGr' class='deleteGr'><p>Supprimer le groupe</p></a>
                    <a id='addUserGr'><div>Ajouter membre</div><div style='display:none;'>Supprimer membre</div></a>
                </div>
                {% endif %}
                {% if chat.adm != user %}
                    <a id='deleteGr' class='deleteGr'><p>Sortir du groupe</p></a>
                {% endif %}
                    <h4 class='members'>{{chat.users.all.count}} membres</h4>
                    <ul class='members'>
                        {% for member in chat.users.all %}
                            <li class="user"> 
                                {{member|capfirst}} 
                                {% if chat.adm == user and member != chat.adm %}
                                <img id='{{member}}' src="{% static "images/delete.png" %}" alt="deleteicon">
                                {% endif %}
                                {% if chat.adm != user and member == chat.adm %}
                                (adm)
                                {% endif %}
                            </li>
                        {% endfor %}
                    </ul> 
                {% if chat.adm == user %}
                    <ul class='asideadm'>
                        {% for user in users %}
                        {% if user not in chat.users.all %}
                            <li>{{ user|capfirst }}<a><input type="checkbox" class="option" value="{{ user }}"/></a></li>
                        {% endif %}
                        {% endfor %}
                    </ul>
                    <img id='addUserGrBtn' src="{% static "images/save.png" %}" alt="deleteicon">
                {% endif %}
            </div>
            {% else %}
            <div class="userinfo">
                {% for elem in chat.users.all %}
                    {% if user != elem %}
                <div>
                    <h3>{{ elem.get_username|capfirst }}</h3>
                </div>
                <div>
                    <h5>Info</h5>
                    <p>
                        {% if not elem.info %}
                            Non renseigné
                        {% endif %}
                        {{ elem.info }}
                    </p>
                </div>
                <div>
                    <h5>Mail</h5>
                    <p>
                        {% if not elem.email %}
                            Non renseigné
                        {% endif %}
                        {{ elem.email }}
                    </p>
                </div>
                <div>
                    <h5>Téléphone</h5>
                    <p>
                        {% if not elem.num_tel %}
                            Non renseigné
                        {% endif %}
                        {{ elem.num_tel }}
                    </p>
                </div>
                    {% endif %}
                {% endfor %}
                <a id='deleteGr' class='deleteGr'><p>Supprimer le chat</p></a>
            </div>  
            {% endif %}
        </aside>
        <div class="readMsg">
            <ul id='id{{chat.uuid}}'>
            {% regroup messages by date as msg_list %}
            {% for date_group in msg_list %}
                <li class="dateMsg"><span>{{date_group.grouper}}</span></li>
                {% for msg in date_group.list %}
                    {% if msg.content.type != 'normal' %}
                        {% if msg.content.user != user and msg.content.type == 'join' %}
                <li class="info">{{msg.content}}</li>
                        {% elif msg.content.user == user and msg.content.type == 'create' %}
                <li class="info">{{msg.content}}</li>
                        {% elif msg.content.type == 'left' and msg.content.user != user %}
                <li class="info">{{msg.content}}</li>
                        {% elif msg.content.type == 'info' %}
                <li class="info">{{msg.content}}</li>
                        {% endif %}
                    {% else %}
                        {% if msg.content.user == user %}
                <li class="mymessage">
                    <p>{{ msg.content }}</p>
                    <span>{{ msg.content.timestamp.time }} </span>
                            {% if msg.content.status == 'delivered' or msg.content.status == 'received' %}
                    <span class='seen'>o</span>
                            {% else %}
                    <span>o</span>
                            {% endif %}
                            {% if msg.content.status == 'received' %}
                    <span class='seen'>o</span>
                            {% else %}
                    <span>o</span>
                            {% endif %}
                        {% else %}
                <li class="yourmessage">
                            {% if chat.groupe %}
                    <span class='spanuser'>@{{msg.content.user|capfirst}}</span>
                            {% endif %}
                    <p>{{ msg.content }}</p>
                    <span>{{ msg.content.timestamp.time }} </span>
                        {% endif %}
                </li>
                    {% endif %}
                {% endfor %}
            {% endfor %}
            </ul>
        </div>
        <div class="inputMsg">
            <div >
                <textarea name="text" placeholder="Taper le message..." maxlength="2000" required id="id_text"></textarea>
                <input id='inputMsgBtn' class='inputMsgBtn' type="image" src="{% static 'images/sender.png' %}" name="submit" alt="Envoyer">
            </div>
        </div>
    </section>


    